site_name: Crônicas de Westeros
site_url: https://cronicasdewesteros.github.io/cronicasdewesteros/

theme:
  name: material
  language: pt
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate

nav:
  - Início: index.md

  - Lore:
      - Visão Geral: lore/index.md
      - História Cronológica: lore/historia.md
      - Facções: /lore/faccoes.md

  - Casas:
      - Visão Geral: casas/index.md
      - Casa Stark: casas/stark.md
      - Casa Lannister: casas/lannister.md
      - Casa Seaworth: casas/seaworth.md
      - Casa Stokeworth: casas/stokeworth.md
      - Casa Tarly: casas/tarly.md
      
  - Como Jogar: como-jogar.md