site_name: Crônicas de Westeros
site_url: https://cronicasdewesteros.github.io/cronicasdewesteros/

theme:
  name: material
  language: pt
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate

nav:
  - Início: index.md

  - Lore:
      - Visão Geral: lore/index.md
      - História Cronológica: lore/historia.md

  - Casas:
      - Visão Geral: casas/index.md
      - Casa Stark: casas/stark.md
      - Casa Lannister: casas/lannister.md
      - Casa Seaworth: casas/seaworth.md
      - Casa Stokeworth: casas/stokeworth.md
      - Casa Tarly: casas/tarly.md

  - Facções:
      - Visão Geral: faccoes/index.md
      - Facções Stark: faccoes/stark.md
      - Facções Lannister: faccoes/lannister.md
      - Facções Stokeworth: faccoes/stokeworth.md
      - Facções Seaworth: faccoes/seaworth.md
      - Facções Tarly: faccoes/tarly.md

  - Personagens:
      - Visão Geral: personagens/index.md
      - Starks: personagens/starks.md

  - Como Jogar: como-jogar.md