site_name: Crônicas de Westeros
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Início: index.md
  - Lore:
      - Visão Geral: lore/index.md
      - História: lore/historia.md
      - Facções: lore/faccoes.md
  - Regras:
      - Comece Aqui: regras/index.md
      - Atributos: regras/atributos.md
      - Habilidades: regras/habilidades.md
      - Exércitos: regras/exercitos.md
      - Casas: regras/casas.md
  - Casas:
      - Casa Stark: casas/stark.md
      - Casa X: casas/casa_x.md
  - Como Jogar: como-jogar.md